# Generated by Django 3.0.5 on 2020-05-12 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userPlaylist',
            fields=[
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('playlistId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sharedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('slug', models.SlugField(unique=True)),
                ('rating', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('artists', models.CharField(max_length=100)),
                ('songId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovbeat.userPlaylist')),
            ],
        ),
    ]
