# Generated by Django 3.0.5 on 2020-05-14 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('playlistId', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('json', models.CharField(max_length=10000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sharedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('rating', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('songId', models.CharField(max_length=100, null=True)),
                ('json', models.CharField(max_length=100000)),
                ('songAutoId', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovbeat.UserPlaylist')),
            ],
        ),
    ]
